Mayhem Integration
mayhemheroes/zstd-rs pull request #1
Opened 2022-05-16 22:41 UTC by ebell495

2022-05-29 21:16 UTC, xansec requested changes

2022-05-29 21:16 UTC, xansec commented on Mayhemfile
> +cmds:
There should only be one target per Mayhemfile. Please either omit one target or split into two Mayhemfiles (as described here: https://community.forallsecure.com/t/error-the-mayhem-for-code-scan-detected-the-mayhem-run-for-your-target-was-unsuccessful-and-multiple-docker-files-in-the-repository/350/5)

2022-05-29 21:16 UTC, xansec commented on Mayhemfile
> +cmds:
Also make sure that the target name reflects the command being run.

2022-05-30 01:42 UTC, ebell495 commented
I've separated the targets and fixed the names.

2022-05-30 04:31 UTC, xansec commented
LGTM!

2022-05-30 04:31 UTC, merged